[theme]
base = "light"
primaryColor = "#0984e3"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#F7F9FC"
textColor = "#1F2937"
font = "sans serif"

[browser]
serverAddress = "localhost"
serverPort = 8501

[server]
headless = true
enableCORS = false

[ui]
hideSidebarNav = false

